# Copyright (c) 2021 Contributors to the Eclipse Foundation
#
# This program and the accompanying materials are made
# available under the terms of the Apache Software License 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: Apache-2.0

# Config file used by .github/workflows/labeler.yml

# This file matches file/folder changes to labels. See https://github.com/actions/labeler for more information.

# e.g to add the test label to any changes in the /tests directory:

# test:
# - changed-files:
#   - tests/*

ghActions:
- changed-files:
    - any-glob-to-any-file: [.github/workflows/**/*]
documentation:
- changed-files:
    - any-glob-to-any-file: [docs/**/*, docs/*, '**/*.md']
jenkins-pipeline:
    - changed-files:
        - any-glob-to-any-file: [pipelines/**/*, pipelines/*]
generation:
    - changed-files:
        - any-glob-to-any-file: [pipelines/build/regeneration/*, pipelines/build/common/config_regeneration.groovy]
docker:
    - changed-files:
        - any-glob-to-any-file: [pipelines/build/dockerFiles/*]
testing:
    - changed-files:
        - any-glob-to-any-file: [pipelines/build/prTester/*, pipelines/src/test/*]
code-tools:
    - changed-files:
        - any-glob-to-any-file: [tools/*]
gradle:
    - changed-files:
        - any-glob-to-any-file: [pipelines/gradle/*, pipelines/build.gradle, pipelines/gradlew]
cross-compile:
    - changed-files:
        - any-glob-to-any-file: [pipelines/build/common/cross_compiled_version_out.groovy]
