# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# This program and the accompanying materials are made
# available under the terms of the Apache Software License 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: Apache-2.0

header:
  license:
    spdx-id: Apache-2.0-EF
    copyright-owner: Contributors to the Eclipse Foundation
      
  comment: on-failure

  paths-ignore:
    - 'LICENSE'
    - 'NOTICE'
    - '**/*.md'
    - '.github/linters/*'
    - '.gitignore'
    - '**/*.dia'
    - '**/*.patch'
