
on:
  pull_request_target:
    types: [ opened ]

jobs:
  comment:
    name: Add Comment
    runs-on: ubuntu-latest

    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Thank you for creating a pull request!
            In order to run the [pipeline tests](https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/tree/master/pipelines/build/prTester#openjdk-build-pr-tester) I require an admin to post the following comment: `run tests`
